sudo: required

services:
  - docker

script:
  - docker build -t appium .
  - docker run -d --name appium_android appium
  - docker ps -a
  - docker exec appium_android /bin/sh -c "appium-doctor --android"
  - docker exec appium_android /bin/sh -c "android list"
  - docker exec appium_android /bin/sh -c "adb devices"
