sudo: false

services:
  - docker
  
language: bash

before_install:
  - docker -v
  
script:
  - docker build -t "appium/appium:latest" -f Appium/Dockerfile .
  - docker build -t "appium/appium-emulator:latest" -f AppiumEmulator/Dockerfile .
  
after_success:
  - if [[ $TRAVIS_PULL_REQUEST == "false" ]] && [[ "$TRAVIS_TAG" != "" ]]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag "appium/appium:latest" "appium/appium:$TRAVIS_TAG" && docker push "appium/appium:$TRAVIS_TAG" ;
    docker tag "appium/appium-emulator:latest" "appium/appium-emulator:$TRAVIS_TAG" && docker push "appium/appium-emulator:$TRAVIS_TAG" ;
    fi
    
  - if [[ $TRAVIS_BRANCH == 'master' ]] && [[ $TRAVIS_PULL_REQUEST == "false" ]]; then 
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker tag "appium/appium:latest" "appium/appium:latest" && docker push "appium/appium:latest" ;
    docker tag "appium/appium-emulator:latest" "appium/appium-emulator:latest" && docker push "appium/appium-emulator:latest" ;
    fi
    
  - if [[ $TRAVIS_PULL_REQUEST == "true" ]]; then 
    docker images;
    fi
